// Carpentry tools: G-code generation for common woodworking joinery and operations

import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { z } from "zod";
import { client } from "../cncjs-client.js";

function text(s: string) {
  return { content: [{ type: "text" as const, text: s }] };
}

function err(s: string) {
  return { content: [{ type: "text" as const, text: s }], isError: true };
}

// ── G-code helpers ──────────────────────────────────────────

const SAFE_Z = 5;

function gcodeHeader(spindleSpeed: number): string[] {
  return [
    "; Generated by CNC-design-control-MCP",
    "G90 G21 ; Absolute positioning, millimeters",
    "G17 ; XY plane",
    `G0 Z${SAFE_Z} ; Retract to safe height`,
    `M3 S${spindleSpeed} ; Spindle on CW`,
    "G4 P2 ; Dwell 2s for spindle to reach speed",
  ];
}

function gcodeFooter(): string[] {
  return [
    `G0 Z${SAFE_Z} ; Retract to safe height`,
    "M5 ; Spindle off",
    "G0 X0 Y0 ; Return to origin",
    "M2 ; Program end",
  ];
}

// ── Geometry helpers ────────────────────────────────────────

function rasterPocket(
  xStart: number, yStart: number,
  xEnd: number, yEnd: number,
  currentDepth: number, stepOverDist: number, feedrate: number
): string[] {
  const gcode: string[] = [];
  gcode.push(`G0 X${xStart.toFixed(3)} Y${yStart.toFixed(3)}`);
  gcode.push(`G1 Z${(-currentDepth).toFixed(3)} F${Math.round(feedrate / 3)}`);

  let y = yStart;
  let leftToRight = true;
  while (y <= yEnd + 0.001) {
    const clampedY = Math.min(y, yEnd);
    if (leftToRight) {
      gcode.push(`G1 X${xEnd.toFixed(3)} Y${clampedY.toFixed(3)} F${feedrate}`);
    } else {
      gcode.push(`G1 X${xStart.toFixed(3)} Y${clampedY.toFixed(3)} F${feedrate}`);
    }
    y += stepOverDist;
    if (y <= yEnd + 0.001) {
      gcode.push(`G1 Y${Math.min(y, yEnd).toFixed(3)} F${feedrate}`);
    }
    leftToRight = !leftToRight;
  }
  return gcode;
}

export function registerCarpentryTools(server: McpServer): void {
  // ── generate_dado ─────────────────────────────────────────

  server.tool(
    "generate_dado",
    "Generate G-code for a dado (rectangular groove/channel). Used for shelves, dividers, and panel joinery. Cuts a flat-bottomed channel across the workpiece.",
    {
      startX: z.number().describe("Groove start X position (mm)"),
      startY: z.number().describe("Groove start Y position (mm)"),
      length: z.number().positive().describe("Groove length along cutting direction (mm)"),
      width: z.number().positive().describe("Groove width — should match mating panel thickness (mm)"),
      depth: z.number().positive().describe("Groove depth — typically 1/3 to 1/2 of stock thickness (mm)"),
      direction: z.enum(["x", "y"]).default("x").describe("Cutting direction: x (horizontal) or y (vertical)"),
      stepDown: z.number().positive().describe("Depth per pass (mm)"),
      feedrate: z.number().positive().describe("Cutting feed rate (mm/min)"),
      spindleSpeed: z.number().positive().describe("Spindle speed (RPM)"),
      toolDiameter: z.number().positive().describe("Tool diameter (mm) — use straight/flat-bottom bit"),
      autoLoad: z.boolean().default(true).describe("Automatically load into CNCjs (default true)"),
    },
    async (params) => {
      try {
        const { startX, startY, length, width, depth, direction, stepDown, feedrate, spindleSpeed, toolDiameter, autoLoad } = params;
        const stepOverDist = toolDiameter * 0.4;
        const gcode: string[] = [...gcodeHeader(spindleSpeed)];

        // Compute pocket bounds (inset by tool radius)
        const toolR = toolDiameter / 2;
        let xStart: number, yStart: number, xEnd: number, yEnd: number;

        if (direction === "x") {
          xStart = startX + toolR;
          xEnd = startX + length - toolR;
          yStart = startY + toolR;
          yEnd = startY + width - toolR;
        } else {
          xStart = startX + toolR;
          xEnd = startX + width - toolR;
          yStart = startY + toolR;
          yEnd = startY + length - toolR;
        }

        if (xEnd < xStart || yEnd < yStart) {
          return err("Dado too narrow for tool diameter. Use a smaller bit or increase dado width.");
        }

        let currentDepth = 0;
        while (currentDepth < depth) {
          currentDepth = Math.min(currentDepth + stepDown, depth);
          gcode.push(...rasterPocket(xStart, yStart, xEnd, yEnd, currentDepth, stepOverDist, feedrate));
          gcode.push(`G0 Z${SAFE_Z}`);
        }

        gcode.push(...gcodeFooter());
        const gcodeStr = gcode.join("\n");

        if (autoLoad) {
          const name = `dado_${direction}_${Date.now()}.nc`;
          client.loadGcode(name, gcodeStr);
          return text(`Dado G-code generated and loaded (${gcode.length} lines, ${length}x${width}x${depth}mm ${direction}-direction).\nUse start_job to execute.\n\nPreview:\n${gcodeStr}`);
        }
        return text(`Dado G-code generated (${gcode.length} lines):\n\n${gcodeStr}`);
      } catch (e: any) {
        return err(e.message);
      }
    }
  );

  // ── generate_rabbet ───────────────────────────────────────

  server.tool(
    "generate_rabbet",
    "Generate G-code for a rabbet (L-shaped step cut along a workpiece edge). Used for back panels, lid recesses, and lap joints.",
    {
      edge: z.enum(["top", "bottom", "left", "right"]).describe("Which edge of the workpiece to cut the rabbet on"),
      workpieceWidth: z.number().positive().describe("Workpiece dimension in X (mm)"),
      workpieceHeight: z.number().positive().describe("Workpiece dimension in Y (mm)"),
      rabbetWidth: z.number().positive().describe("Rabbet width — step inward from edge (mm)"),
      rabbetDepth: z.number().positive().describe("Rabbet depth (mm)"),
      stepDown: z.number().positive().describe("Depth per pass (mm)"),
      feedrate: z.number().positive().describe("Cutting feed rate (mm/min)"),
      spindleSpeed: z.number().positive().describe("Spindle speed (RPM)"),
      toolDiameter: z.number().positive().describe("Tool diameter (mm)"),
      autoLoad: z.boolean().default(true).describe("Automatically load into CNCjs (default true)"),
    },
    async (params) => {
      try {
        const { edge, workpieceWidth, workpieceHeight, rabbetWidth, rabbetDepth, stepDown, feedrate, spindleSpeed, toolDiameter, autoLoad } = params;
        const stepOverDist = toolDiameter * 0.4;
        const toolR = toolDiameter / 2;
        const gcode: string[] = [...gcodeHeader(spindleSpeed)];

        // Determine pocket bounds based on edge (tool center lines, inset by radius)
        let xStart: number, yStart: number, xEnd: number, yEnd: number;

        switch (edge) {
          case "bottom":
            xStart = toolR; xEnd = workpieceWidth - toolR;
            yStart = toolR; yEnd = rabbetWidth - toolR;
            break;
          case "top":
            xStart = toolR; xEnd = workpieceWidth - toolR;
            yStart = workpieceHeight - rabbetWidth + toolR; yEnd = workpieceHeight - toolR;
            break;
          case "left":
            xStart = toolR; xEnd = rabbetWidth - toolR;
            yStart = toolR; yEnd = workpieceHeight - toolR;
            break;
          case "right":
            xStart = workpieceWidth - rabbetWidth + toolR; xEnd = workpieceWidth - toolR;
            yStart = toolR; yEnd = workpieceHeight - toolR;
            break;
        }

        if (xEnd < xStart || yEnd < yStart) {
          return err("Rabbet too narrow for tool diameter. Use a smaller bit or increase rabbet width.");
        }

        let currentDepth = 0;
        while (currentDepth < rabbetDepth) {
          currentDepth = Math.min(currentDepth + stepDown, rabbetDepth);
          gcode.push(...rasterPocket(xStart, yStart, xEnd, yEnd, currentDepth, stepOverDist, feedrate));
          gcode.push(`G0 Z${SAFE_Z}`);
        }

        gcode.push(...gcodeFooter());
        const gcodeStr = gcode.join("\n");

        if (autoLoad) {
          const name = `rabbet_${edge}_${Date.now()}.nc`;
          client.loadGcode(name, gcodeStr);
          return text(`Rabbet G-code generated and loaded (${gcode.length} lines, ${edge} edge, ${rabbetWidth}x${rabbetDepth}mm).\nUse start_job to execute.\n\nPreview:\n${gcodeStr}`);
        }
        return text(`Rabbet G-code generated (${gcode.length} lines):\n\n${gcodeStr}`);
      } catch (e: any) {
        return err(e.message);
      }
    }
  );

  // ── generate_mortise ──────────────────────────────────────

  server.tool(
    "generate_mortise",
    "Generate G-code for a mortise (rectangular pocket for mortise-and-tenon joinery). Precisely sized pocket with multi-pass step-down.",
    {
      centerX: z.number().describe("Mortise center X position (mm)"),
      centerY: z.number().describe("Mortise center Y position (mm)"),
      length: z.number().positive().describe("Mortise length — along grain, matches tenon length (mm)"),
      width: z.number().positive().describe("Mortise width — matches tenon thickness (mm)"),
      depth: z.number().positive().describe("Mortise depth — slightly deeper than tenon for glue space (mm)"),
      stepDown: z.number().positive().describe("Depth per pass (mm)"),
      feedrate: z.number().positive().describe("Cutting feed rate (mm/min)"),
      spindleSpeed: z.number().positive().describe("Spindle speed (RPM)"),
      toolDiameter: z.number().positive().describe("Tool diameter (mm) — use upcut spiral bit"),
      autoLoad: z.boolean().default(true).describe("Automatically load into CNCjs (default true)"),
    },
    async (params) => {
      try {
        const { centerX, centerY, length, width, depth, stepDown, feedrate, spindleSpeed, toolDiameter, autoLoad } = params;
        const toolR = toolDiameter / 2;
        const stepOverDist = toolDiameter * 0.4;
        const gcode: string[] = [...gcodeHeader(spindleSpeed)];

        const xStart = centerX - length / 2 + toolR;
        const xEnd = centerX + length / 2 - toolR;
        const yStart = centerY - width / 2 + toolR;
        const yEnd = centerY + width / 2 - toolR;

        if (xEnd < xStart || yEnd < yStart) {
          return err("Mortise too small for tool diameter. Use a smaller bit or increase mortise dimensions.");
        }

        let currentDepth = 0;
        while (currentDepth < depth) {
          currentDepth = Math.min(currentDepth + stepDown, depth);
          gcode.push(...rasterPocket(xStart, yStart, xEnd, yEnd, currentDepth, stepOverDist, feedrate));
          gcode.push(`G0 Z${SAFE_Z}`);
        }

        gcode.push(...gcodeFooter());
        const gcodeStr = gcode.join("\n");

        if (autoLoad) {
          const name = `mortise_${Date.now()}.nc`;
          client.loadGcode(name, gcodeStr);
          return text(`Mortise G-code generated and loaded (${gcode.length} lines, ${length}x${width}x${depth}mm).\nUse start_job to execute.\n\nPreview:\n${gcodeStr}`);
        }
        return text(`Mortise G-code generated (${gcode.length} lines):\n\n${gcodeStr}`);
      } catch (e: any) {
        return err(e.message);
      }
    }
  );

  // ── generate_box_joint ────────────────────────────────────

  server.tool(
    "generate_box_joint",
    "Generate G-code for box joint (finger joint) cuts along a workpiece edge. Creates evenly spaced interlocking fingers for strong corner joints.",
    {
      edge: z.enum(["x", "y"]).describe("Edge direction: x (cuts along X axis) or y (cuts along Y axis)"),
      edgeLength: z.number().positive().describe("Total length of the edge being jointed (mm)"),
      stockThickness: z.number().positive().describe("Material thickness — sets finger depth (mm)"),
      fingerWidth: z.number().positive().describe("Width of each finger (mm) — should be >= tool diameter"),
      startX: z.number().default(0).describe("Starting X position of the edge (mm)"),
      startY: z.number().default(0).describe("Starting Y position of the edge (mm)"),
      cutFingers: z.boolean().default(true).describe("true = cut the finger slots (piece A), false = cut the gaps (piece B, offset by one finger)"),
      stepDown: z.number().positive().describe("Depth per pass (mm)"),
      feedrate: z.number().positive().describe("Cutting feed rate (mm/min)"),
      spindleSpeed: z.number().positive().describe("Spindle speed (RPM)"),
      toolDiameter: z.number().positive().describe("Tool diameter (mm) — use straight bit"),
      autoLoad: z.boolean().default(true).describe("Automatically load into CNCjs (default true)"),
    },
    async (params) => {
      try {
        const { edge, edgeLength, stockThickness, fingerWidth, startX, startY, cutFingers, stepDown, feedrate, spindleSpeed, toolDiameter, autoLoad } = params;

        if (fingerWidth < toolDiameter) {
          return err(`Finger width (${fingerWidth}mm) must be >= tool diameter (${toolDiameter}mm).`);
        }

        const toolR = toolDiameter / 2;
        const stepOverDist = toolDiameter * 0.4;
        const gcode: string[] = [...gcodeHeader(spindleSpeed)];
        const numFingers = Math.floor(edgeLength / fingerWidth);
        const offset = cutFingers ? 0 : 1;
        let slotCount = 0;

        for (let i = offset; i < numFingers; i += 2) {
          const slotStart = i * fingerWidth;
          const slotEnd = slotStart + fingerWidth;

          let xS: number, xE: number, yS: number, yE: number;
          if (edge === "x") {
            xS = startX + slotStart + toolR;
            xE = startX + slotEnd - toolR;
            yS = startY + toolR;
            yE = startY + stockThickness - toolR;
          } else {
            xS = startX + toolR;
            xE = startX + stockThickness - toolR;
            yS = startY + slotStart + toolR;
            yE = startY + slotEnd - toolR;
          }

          if (xE < xS || yE < yS) continue;

          let currentDepth = 0;
          while (currentDepth < stockThickness) {
            currentDepth = Math.min(currentDepth + stepDown, stockThickness);
            gcode.push(...rasterPocket(xS, yS, xE, yE, currentDepth, stepOverDist, feedrate));
            gcode.push(`G0 Z${SAFE_Z}`);
          }
          slotCount++;
        }

        if (slotCount === 0) {
          return err("No finger slots could be generated. Check that finger width >= tool diameter and edge length is sufficient.");
        }

        gcode.push(...gcodeFooter());
        const gcodeStr = gcode.join("\n");

        const label = cutFingers ? "piece A (fingers)" : "piece B (gaps)";
        if (autoLoad) {
          const name = `box_joint_${cutFingers ? "A" : "B"}_${Date.now()}.nc`;
          client.loadGcode(name, gcodeStr);
          return text(`Box joint G-code generated and loaded (${gcode.length} lines, ${slotCount} slots, ${label}).\nUse start_job to execute.\n\nPreview:\n${gcodeStr}`);
        }
        return text(`Box joint G-code generated (${gcode.length} lines, ${slotCount} slots, ${label}):\n\n${gcodeStr}`);
      } catch (e: any) {
        return err(e.message);
      }
    }
  );

  // ── generate_shelf_pin_holes ──────────────────────────────

  server.tool(
    "generate_shelf_pin_holes",
    "Generate G-code for shelf pin hole patterns (two columns of evenly spaced holes for adjustable shelving). Standard 5mm holes at 32mm system spacing.",
    {
      startX: z.number().default(0).describe("X position of first column of holes (mm)"),
      startY: z.number().default(0).describe("Y position of first hole (mm)"),
      columnSpacing: z.number().positive().describe("Distance between the two hole columns (mm) — typically panel width minus 2× edge margin"),
      holeSpacing: z.number().positive().default(32).describe("Vertical spacing between holes (mm, default 32 — standard 32mm system)"),
      holeCount: z.number().int().positive().describe("Number of holes per column"),
      holeDiameter: z.number().positive().default(5).describe("Hole diameter (mm, default 5 for standard shelf pins)"),
      holeDepth: z.number().positive().default(10).describe("Hole depth (mm, default 10)"),
      peckDepth: z.number().positive().optional().describe("Peck drilling depth per cycle (mm). If omitted, drills in one pass."),
      feedrate: z.number().positive().describe("Drilling feed rate (mm/min)"),
      spindleSpeed: z.number().positive().describe("Spindle speed (RPM)"),
      autoLoad: z.boolean().default(true).describe("Automatically load into CNCjs (default true)"),
    },
    async (params) => {
      try {
        const { startX, startY, columnSpacing, holeSpacing, holeCount, holeDepth, peckDepth, feedrate, spindleSpeed, autoLoad } = params;
        const gcode: string[] = [...gcodeHeader(spindleSpeed)];

        const columns = [startX, startX + columnSpacing];
        let totalHoles = 0;

        for (const colX of columns) {
          for (let i = 0; i < holeCount; i++) {
            const y = startY + i * holeSpacing;

            gcode.push(`G0 X${colX.toFixed(3)} Y${y.toFixed(3)}`);
            gcode.push("G0 Z1 ; Approach");

            if (peckDepth) {
              let drilled = 0;
              while (drilled < holeDepth) {
                drilled = Math.min(drilled + peckDepth, holeDepth);
                gcode.push(`G1 Z${(-drilled).toFixed(3)} F${feedrate}`);
                gcode.push("G0 Z1 ; Retract for chip clearing");
              }
            } else {
              gcode.push(`G1 Z${(-holeDepth).toFixed(3)} F${feedrate}`);
            }

            gcode.push(`G0 Z${SAFE_Z}`);
            totalHoles++;
          }
        }

        gcode.push(...gcodeFooter());
        const gcodeStr = gcode.join("\n");

        if (autoLoad) {
          const name = `shelf_pins_${Date.now()}.nc`;
          client.loadGcode(name, gcodeStr);
          return text(`Shelf pin hole G-code generated and loaded (${gcode.length} lines, ${totalHoles} holes in 2 columns, ${holeSpacing}mm spacing).\nUse start_job to execute.\n\nPreview:\n${gcodeStr}`);
        }
        return text(`Shelf pin hole G-code generated (${gcode.length} lines, ${totalHoles} holes):\n\n${gcodeStr}`);
      } catch (e: any) {
        return err(e.message);
      }
    }
  );

  // ── generate_tenon ────────────────────────────────────────

  server.tool(
    "generate_tenon",
    "Generate G-code to cut a tenon on the end of a workpiece by removing material from both faces. Creates the protruding tongue that fits into a mortise.",
    {
      startX: z.number().describe("Workpiece end X position (mm)"),
      startY: z.number().describe("Workpiece edge Y position (mm)"),
      workpieceWidth: z.number().positive().describe("Workpiece width in Y (mm)"),
      stockThickness: z.number().positive().describe("Stock thickness in Z (mm)"),
      tenonLength: z.number().positive().describe("Tenon length — how far it protrudes (mm)"),
      tenonThickness: z.number().positive().describe("Tenon thickness — must be less than stock thickness (mm)"),
      shoulderWidth: z.number().min(0).default(0).describe("Shoulder width on each side in Y (mm, 0 = full-width tenon)"),
      stepDown: z.number().positive().describe("Depth per pass (mm)"),
      feedrate: z.number().positive().describe("Cutting feed rate (mm/min)"),
      spindleSpeed: z.number().positive().describe("Spindle speed (RPM)"),
      toolDiameter: z.number().positive().describe("Tool diameter (mm)"),
      autoLoad: z.boolean().default(true).describe("Automatically load into CNCjs (default true)"),
    },
    async (params) => {
      try {
        const { startX, startY, workpieceWidth, stockThickness, tenonLength, tenonThickness, shoulderWidth, stepDown, feedrate, spindleSpeed, toolDiameter, autoLoad } = params;

        if (tenonThickness >= stockThickness) {
          return err("Tenon thickness must be less than stock thickness.");
        }

        const cheekDepth = (stockThickness - tenonThickness) / 2;
        const toolR = toolDiameter / 2;
        const stepOverDist = toolDiameter * 0.4;
        const gcode: string[] = [...gcodeHeader(spindleSpeed)];

        // Top cheek removal (material above the tenon)
        const xS = startX + toolR;
        const xE = startX + tenonLength - toolR;
        const yS = startY + shoulderWidth + toolR;
        const yE = startY + workpieceWidth - shoulderWidth - toolR;

        if (xE < xS || yE < yS) {
          return err("Tenon dimensions too small for tool diameter.");
        }

        gcode.push("; Top cheek");
        let currentDepth = 0;
        while (currentDepth < cheekDepth) {
          currentDepth = Math.min(currentDepth + stepDown, cheekDepth);
          gcode.push(...rasterPocket(xS, yS, xE, yE, currentDepth, stepOverDist, feedrate));
          gcode.push(`G0 Z${SAFE_Z}`);
        }

        // Side shoulders (if shoulderWidth > 0)
        if (shoulderWidth > 0) {
          // Left shoulder
          const lxS = startX + toolR;
          const lxE = startX + tenonLength - toolR;
          const lyS = startY + toolR;
          const lyE = startY + shoulderWidth - toolR;

          if (lxE >= lxS && lyE >= lyS) {
            gcode.push("; Left shoulder");
            currentDepth = 0;
            while (currentDepth < cheekDepth) {
              currentDepth = Math.min(currentDepth + stepDown, cheekDepth);
              gcode.push(...rasterPocket(lxS, lyS, lxE, lyE, currentDepth, stepOverDist, feedrate));
              gcode.push(`G0 Z${SAFE_Z}`);
            }
          }

          // Right shoulder
          const rxS = startX + toolR;
          const rxE = startX + tenonLength - toolR;
          const ryS = startY + workpieceWidth - shoulderWidth + toolR;
          const ryE = startY + workpieceWidth - toolR;

          if (rxE >= rxS && ryE >= ryS) {
            gcode.push("; Right shoulder");
            currentDepth = 0;
            while (currentDepth < cheekDepth) {
              currentDepth = Math.min(currentDepth + stepDown, cheekDepth);
              gcode.push(...rasterPocket(rxS, ryS, rxE, ryE, currentDepth, stepOverDist, feedrate));
              gcode.push(`G0 Z${SAFE_Z}`);
            }
          }
        }

        gcode.push(...gcodeFooter());
        const gcodeStr = gcode.join("\n");
        const note = "Note: flip workpiece and run again for bottom cheek, or use a jig for two-sided machining.";

        if (autoLoad) {
          const name = `tenon_${Date.now()}.nc`;
          client.loadGcode(name, gcodeStr);
          return text(`Tenon G-code generated and loaded (${gcode.length} lines, ${tenonLength}x${tenonThickness}mm tenon, cheek depth ${cheekDepth.toFixed(1)}mm per side).\n${note}\nUse start_job to execute.\n\nPreview:\n${gcodeStr}`);
        }
        return text(`Tenon G-code generated (${gcode.length} lines):\n${note}\n\n${gcodeStr}`);
      } catch (e: any) {
        return err(e.message);
      }
    }
  );

  // ── generate_dovetail_pins ────────────────────────────────

  server.tool(
    "generate_dovetail_pins",
    "Generate G-code for dovetail pin board waste removal. Cuts the angled waste between pins using a straight bit with linear interpolation to approximate the dovetail angle.",
    {
      edgeLength: z.number().positive().describe("Total length of the joint edge (mm)"),
      stockThickness: z.number().positive().describe("Material thickness — sets cut depth (mm)"),
      pinWidth: z.number().positive().describe("Width of each pin at the narrow end (mm)"),
      tailWidth: z.number().positive().describe("Width of each tail/gap at the narrow end (mm)"),
      dovetailAngle: z.number().min(5).max(20).default(8).describe("Dovetail angle in degrees (default 8° for hardwood, 14° for softwood)"),
      startX: z.number().default(0).describe("Start X position (mm)"),
      startY: z.number().default(0).describe("Start Y position (mm)"),
      stepDown: z.number().positive().describe("Depth per pass (mm)"),
      feedrate: z.number().positive().describe("Cutting feed rate (mm/min)"),
      spindleSpeed: z.number().positive().describe("Spindle speed (RPM)"),
      toolDiameter: z.number().positive().describe("Tool diameter (mm) — use smallest available straight bit"),
      autoLoad: z.boolean().default(true).describe("Automatically load into CNCjs (default true)"),
    },
    async (params) => {
      try {
        const { edgeLength, stockThickness, pinWidth, tailWidth, dovetailAngle, startX, startY, stepDown, feedrate, spindleSpeed, toolDiameter, autoLoad } = params;
        const gcode: string[] = [...gcodeHeader(spindleSpeed)];

        const angleRad = (dovetailAngle * Math.PI) / 180;
        const taper = Math.tan(angleRad) * stockThickness;
        const pitch = pinWidth + tailWidth;
        const numJoints = Math.floor(edgeLength / pitch);
        const toolR = toolDiameter / 2;
        const stepOverDist = toolDiameter * 0.35;
        let slotCount = 0;

        for (let i = 0; i < numJoints; i++) {
          const slotCenter = startX + pinWidth + i * pitch;

          let currentDepth = 0;
          while (currentDepth < stockThickness) {
            currentDepth = Math.min(currentDepth + stepDown, stockThickness);
            const depthRatio = currentDepth / stockThickness;
            const currentTaper = taper * depthRatio;

            const xLeft = slotCenter - tailWidth / 2 + currentTaper + toolR;
            const xRight = slotCenter + tailWidth / 2 - currentTaper - toolR;
            const yS = startY + toolR;
            const yE = startY + stockThickness - toolR;

            if (xRight < xLeft || yE < yS) continue;

            gcode.push(`G0 X${xLeft.toFixed(3)} Y${yS.toFixed(3)}`);
            gcode.push(`G1 Z${(-currentDepth).toFixed(3)} F${Math.round(feedrate / 3)}`);

            let x = xLeft;
            let forward = true;
            while (x <= xRight + 0.001) {
              const cx = Math.min(x, xRight);
              if (forward) {
                gcode.push(`G1 X${cx.toFixed(3)} Y${yE.toFixed(3)} F${feedrate}`);
              } else {
                gcode.push(`G1 X${cx.toFixed(3)} Y${yS.toFixed(3)} F${feedrate}`);
              }
              x += stepOverDist;
              if (x <= xRight + 0.001) {
                gcode.push(`G1 X${Math.min(x, xRight).toFixed(3)} F${feedrate}`);
              }
              forward = !forward;
            }

            gcode.push(`G0 Z${SAFE_Z}`);
          }
          slotCount++;
        }

        if (slotCount === 0) {
          return err("No dovetail slots could be generated. Check dimensions.");
        }

        gcode.push(...gcodeFooter());
        const gcodeStr = gcode.join("\n");

        if (autoLoad) {
          const name = `dovetail_pins_${Date.now()}.nc`;
          client.loadGcode(name, gcodeStr);
          return text(`Dovetail pin board G-code generated and loaded (${gcode.length} lines, ${slotCount} tail slots, ${dovetailAngle}° angle).\nUse start_job to execute.\n\nPreview:\n${gcodeStr}`);
        }
        return text(`Dovetail pin board G-code generated (${gcode.length} lines, ${slotCount} slots):\n\n${gcodeStr}`);
      } catch (e: any) {
        return err(e.message);
      }
    }
  );

  // ── generate_inlay_pocket ─────────────────────────────────

  server.tool(
    "generate_inlay_pocket",
    "Generate G-code for an inlay pocket — a precisely sized shallow recess for inlaying contrasting material. Supports circle, rectangle, or custom path shapes.",
    {
      shape: z.enum(["circle", "rectangle"]).describe("Pocket shape"),
      centerX: z.number().describe("Pocket center X (mm)"),
      centerY: z.number().describe("Pocket center Y (mm)"),
      width: z.number().positive().optional().describe("Width for rectangle (mm)"),
      height: z.number().positive().optional().describe("Height for rectangle (mm)"),
      radius: z.number().positive().optional().describe("Radius for circle (mm)"),
      depth: z.number().positive().describe("Pocket depth — typically 1-3mm for inlays (mm)"),
      tolerance: z.number().default(0.1).describe("Extra clearance per side for inlay fit (mm, default 0.1)"),
      stepDown: z.number().positive().describe("Depth per pass (mm)"),
      feedrate: z.number().positive().describe("Cutting feed rate (mm/min)"),
      spindleSpeed: z.number().positive().describe("Spindle speed (RPM)"),
      toolDiameter: z.number().positive().describe("Tool diameter (mm) — use small straight or downcut bit for clean edges"),
      autoLoad: z.boolean().default(true).describe("Automatically load into CNCjs (default true)"),
    },
    async (params) => {
      try {
        const { shape, centerX, centerY, depth, tolerance, stepDown, feedrate, spindleSpeed, toolDiameter, autoLoad } = params;
        const toolR = toolDiameter / 2;
        const stepOverDist = toolDiameter * 0.35;
        const gcode: string[] = [...gcodeHeader(spindleSpeed)];

        if (shape === "rectangle") {
          if (!params.width || !params.height) return err("Width and height required for rectangle inlay pocket.");
          const w = params.width + 2 * tolerance;
          const h = params.height + 2 * tolerance;
          const xS = centerX - w / 2 + toolR;
          const xE = centerX + w / 2 - toolR;
          const yS = centerY - h / 2 + toolR;
          const yE = centerY + h / 2 - toolR;

          if (xE < xS || yE < yS) return err("Pocket too small for tool diameter.");

          let currentDepth = 0;
          while (currentDepth < depth) {
            currentDepth = Math.min(currentDepth + stepDown, depth);
            gcode.push(...rasterPocket(xS, yS, xE, yE, currentDepth, stepOverDist, feedrate));
            gcode.push(`G0 Z${SAFE_Z}`);
          }
        } else {
          if (!params.radius) return err("Radius required for circle inlay pocket.");
          const r = params.radius + tolerance;
          const maxR = r - toolR;
          if (maxR <= 0) return err("Pocket too small for tool diameter.");

          let currentDepth = 0;
          while (currentDepth < depth) {
            currentDepth = Math.min(currentDepth + stepDown, depth);
            gcode.push(`G0 X${centerX.toFixed(3)} Y${centerY.toFixed(3)}`);
            gcode.push(`G1 Z${(-currentDepth).toFixed(3)} F${Math.round(feedrate / 3)}`);

            // Spiral out
            let cr = stepOverDist;
            while (cr <= maxR) {
              const segments = Math.max(36, Math.round(2 * Math.PI * cr / 2));
              for (let i = 0; i <= segments; i++) {
                const angle = (2 * Math.PI * i) / segments;
                const expandR = Math.min(cr + (stepOverDist * i) / segments, maxR);
                const px = centerX + expandR * Math.cos(angle);
                const py = centerY + expandR * Math.sin(angle);
                gcode.push(`G1 X${px.toFixed(3)} Y${py.toFixed(3)} F${feedrate}`);
              }
              cr += stepOverDist;
            }

            // Final perimeter
            const segments = 72;
            for (let i = 0; i <= segments; i++) {
              const angle = (2 * Math.PI * i) / segments;
              gcode.push(`G1 X${(centerX + maxR * Math.cos(angle)).toFixed(3)} Y${(centerY + maxR * Math.sin(angle)).toFixed(3)} F${feedrate}`);
            }

            gcode.push(`G0 Z${SAFE_Z}`);
          }
        }

        gcode.push(...gcodeFooter());
        const gcodeStr = gcode.join("\n");

        if (autoLoad) {
          const name = `inlay_pocket_${shape}_${Date.now()}.nc`;
          client.loadGcode(name, gcodeStr);
          return text(`Inlay pocket G-code generated and loaded (${gcode.length} lines, ${shape}, ${depth}mm deep, ${tolerance}mm tolerance).\nUse start_job to execute.\n\nPreview:\n${gcodeStr}`);
        }
        return text(`Inlay pocket G-code generated (${gcode.length} lines):\n\n${gcodeStr}`);
      } catch (e: any) {
        return err(e.message);
      }
    }
  );
}
